task:
  id: resource_verification
  description: "Automatically verify recent resources."
  connectors:
    - GoogleDrive
    - Gmail
  action:
    type: "auto_execute"
    on_error: "manual_review"
  parameters:
    days_back: 7
