tasks:
  - task_id: autoDocSummarizer
    action: "extract_exact_quotes"
    connectors: connector_settings.json
    input_resources: resource_list.md
    auto_execute: true
    required_fields: ["exact_quotes", "financial_figures", "employee_names"]


